#include <iostream>

#include "Tiny16.h"
#include "Tiny16TargetMachine.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"

#include "Tiny16InstrInfo.h"

using namespace llvm;

#define DEBUG_TYPE "tiny16-isel"
#define PASS_NAME "Tiny16 DAG->DAG Pattern Instruction Selection"

/// Tiny16DAGToDAGISel - Tiny16 specific code to select Tiny16 machine
/// instructions for SelectionDAG operations.
///
namespace {
class Tiny16DAGToDAGISel : public SelectionDAGISel {
  const Tiny16Subtarget *Subtarget;

public:
  Tiny16DAGToDAGISel() = delete;
  explicit Tiny16DAGToDAGISel(Tiny16TargetMachine &TM)
      : SelectionDAGISel(TM), Subtarget(TM.getSubtargetImpl()) {}

  void Select(SDNode *N) override;

  bool SelectADDRrr(SDValue Addr, SDValue &Base, SDValue &Offset);
  bool SelectADDRri(SDValue Addr, SDValue &Base, SDValue &Offset);

  bool runOnMachineFunction(MachineFunction &MF) override {
    std::cout << "[TINY16] Tiny16DAGToDAGISel::runOnMachineFunction called\n";
    Subtarget = &MF.getSubtarget<Tiny16Subtarget>();
    return SelectionDAGISel::runOnMachineFunction(MF);
  }

private:
  void SelectMoveImmediate(SDNode *N);
  // SelectConditionalBranch is not needed as it is handled by custom lowering
  // to Tiny16ISD::BR_CC

// Include the pieces autogenerated from the target description.
#include "Tiny16GenDAGISel.inc"
};

class Tiny16DAGToDAGISelLegacy : public SelectionDAGISelLegacy {
public:
  static char ID;
  explicit Tiny16DAGToDAGISelLegacy(Tiny16TargetMachine &tm)
      : SelectionDAGISelLegacy(ID, std::make_unique<Tiny16DAGToDAGISel>(tm)) {}
};
} // end anonymous namespace

char Tiny16DAGToDAGISelLegacy::ID = 0;
INITIALIZE_PASS(Tiny16DAGToDAGISelLegacy, DEBUG_TYPE, PASS_NAME, false, false)

bool Tiny16DAGToDAGISel::SelectADDRri(SDValue Addr, SDValue &Base,
                                      SDValue &Offset) {
  if (FrameIndexSDNode *FIN = dyn_cast<FrameIndexSDNode>(Addr)) {
    Base = CurDAG->getTargetFrameIndex(
        FIN->getIndex(), TLI->getPointerTy(CurDAG->getDataLayout()));
    Offset = CurDAG->getTargetConstant(0, SDLoc(Addr), MVT::i16);
    return true;
  }
  if (Addr.getOpcode() == ISD::TargetExternalSymbol ||
      Addr.getOpcode() == ISD::TargetGlobalAddress ||
      Addr.getOpcode() == ISD::TargetGlobalTLSAddress)
    return false; // direct calls.

  if (Addr.getOpcode() == ISD::ADD || Addr.getOpcode() == ISD::OR) {
    if (ConstantSDNode *CN = dyn_cast<ConstantSDNode>(Addr.getOperand(1))) {
      if (isInt<16>(CN->getSExtValue())) {
        if (FrameIndexSDNode *FIN =
                dyn_cast<FrameIndexSDNode>(Addr.getOperand(0))) {
          // Constant offset from frame ref.
          Base = CurDAG->getTargetFrameIndex(
              FIN->getIndex(),
              getTargetLowering()->getPointerTy(CurDAG->getDataLayout()));
        } else {
          Base = Addr.getOperand(0);
        }
        Offset = CurDAG->getTargetConstant(CN->getSExtValue(), SDLoc(Addr),
                                           MVT::i16);
        return true;
      }
    }
  }
  Base = Addr;
  Offset = CurDAG->getTargetConstant(0, SDLoc(Addr), MVT::i16);
  return true;
}

bool Tiny16DAGToDAGISel::SelectADDRrr(SDValue Addr, SDValue &R1, SDValue &R2) {
  llvm_unreachable("SelectADDRrr not implemented yet");
  // if (Addr.getOpcode() == ISD::FrameIndex) return false;
  // if (Addr.getOpcode() == ISD::TargetExternalSymbol ||
  //     Addr.getOpcode() == ISD::TargetGlobalAddress ||
  //     Addr.getOpcode() == ISD::TargetGlobalTLSAddress)
  //   return false;  // direct calls.

  // if (Addr.getOpcode() == ISD::ADD) {
  //   if (ConstantSDNode *CN = dyn_cast<ConstantSDNode>(Addr.getOperand(1)))
  //     if (isInt<13>(CN->getSExtValue()))
  //       return false;  // Let the reg+imm pattern catch this!
  //   if (Addr.getOperand(0).getOpcode() == SPISD::Lo ||
  //       Addr.getOperand(1).getOpcode() == SPISD::Lo)
  //     return false;  // Let the reg+imm pattern catch this!
  //   R1 = Addr.getOperand(0);
  //   R2 = Addr.getOperand(1);
  //   return true;
  // }

  // R1 = Addr;
  // R2 = CurDAG->getRegister(SP::G0,
  // TLI->getPointerTy(CurDAG->getDataLayout()));
  return false;
}

void Tiny16DAGToDAGISel::SelectMoveImmediate(SDNode *N) {
  std::cout << "[TINY16] Tiny16DAGToDAGISel::SelectMoveImmediate called\n";
  // Make sure the immediate size is supported.
  ConstantSDNode *ConstVal = cast<ConstantSDNode>(N);
  uint64_t ImmVal = ConstVal->getZExtValue();
  uint64_t SupportedMask = 0xfffff;
  if ((ImmVal & SupportedMask) != ImmVal) {
    return SelectCode(N);
  }

  // Special case for 0 - use R0
  if (ImmVal == 0) {
    ReplaceNode(N, CurDAG->getRegister(Tiny16::R0, N->getValueType(0))
                       .getNode()); // Special case: 0 - use R0
    return;
  }

  // If value is less than 256, use only movlo
  // Select the low part of the immediate move.
  uint64_t LoMask = 0xff;
  uint64_t HiMask = 0xff00;
  uint64_t ImmLo = (ImmVal & LoMask);
  uint64_t ImmHi = (ImmVal & HiMask) >> 8;
  SDValue ConstLo = CurDAG->getTargetConstant(ImmLo, N, MVT::i16);
  MachineSDNode *Move =
      CurDAG->getMachineNode(Tiny16::MOVI, N, MVT::i16, ConstLo);

  if (ImmVal > 256) {
    SDValue ConstHi = CurDAG->getTargetConstant(ImmHi, N, MVT::i16);
    Move = CurDAG->getMachineNode(Tiny16::MOVHI, N, MVT::i16, SDValue(Move, 0),
                                  ConstHi);
  }

  ReplaceNode(N, Move);
}

void Tiny16DAGToDAGISel::Select(SDNode *N) {
  std::cout << "[TINY16] Tiny16DAGToDAGISel::Select called\n";
  switch (N->getOpcode()) {
  case ISD::Constant:
    SelectMoveImmediate(N);
    return;
    // ISD::BR_CC is handled by Lowering -> Tiny16ISD::BR_CC -> SelectCode
    // matches pattern
  }

  SelectCode(N);
}

// createTiny16ISelDag - This pass converts a legalized DAG into a
// Tiny16-specific DAG, ready for instruction scheduling.

FunctionPass *llvm::createTiny16ISelDag(Tiny16TargetMachine &TM) {
  std::cout << "[TINY16] createTiny16ISelDag called\n";
  return new Tiny16DAGToDAGISelLegacy(TM);
}
