//===-- LEGSubtarget.h - Define Subtarget for the LEG -------*- C++ -*-===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the LEG specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef TINY16SUBTARGET_H
#define TINY16SUBTARGET_H

#include "Tiny16.h"                           //
#include "Tiny16FrameLowering.h"              //
#include "Tiny16ISelLowering.h"               //
#include "Tiny16InstrInfo.h"                  //
#include "Tiny16SelectionDAGInfo.h"           //
#include "llvm/CodeGen/TargetSubtargetInfo.h" //
#include "llvm/Target/TargetMachine.h"        //
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "Tiny16GenSubtargetInfo.inc"

namespace llvm {
class StringRef;

class Tiny16Subtarget : public Tiny16GenSubtargetInfo {
  virtual void anchor();

private:
  Tiny16InstrInfo InstrInfo;
  Tiny16TargetLowering TLInfo;
  Tiny16SelectionDAGInfo TSInfo;
  Tiny16FrameLowering FrameLowering;
  // InstrItineraryData InstrItins;

public:
  /// This constructor initializes the data members to match that
  /// of the specified triple.
  ///
  Tiny16Subtarget(const StringRef &CPU, const StringRef &TuneCPU,
                  const StringRef &FS, const Tiny16TargetMachine &TM);

  /// getInstrItins - Return the instruction itineraries based on subtarget
  /// selection.
  // const InstrItineraryData *getInstrItineraryData() const override {
  //   return &InstrItins;
  // }
  const Tiny16InstrInfo *getInstrInfo() const override { return &InstrInfo; }
  const Tiny16RegisterInfo *getRegisterInfo() const override {
    return &InstrInfo.getRegisterInfo();
  }
  const Tiny16TargetLowering *getTargetLowering() const override {
    return &TLInfo;
  }
  const Tiny16FrameLowering *getFrameLowering() const override {
    return &FrameLowering;
  }
  const Tiny16SelectionDAGInfo *getSelectionDAGInfo() const override {
    return &TSInfo;
  }

  /// ParseSubtargetFeatures - Parses features string setting specified
  /// subtarget options.  Definition of function is auto generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef TuneCPU, StringRef FS);
};
} // namespace llvm

#endif
